import React, { useState } from "react";
import { InstagramPlan } from "../types";
import { Copy, Check, Sparkles, AlertCircle, FileText, Share2, Layers, Video, MessageSquare } from "lucide-react";

interface Props {
  plan: InstagramPlan;
  activeHookType: "curiosity" | "visual" | "relatable";
  onSelectHookType: (type: "curiosity" | "visual" | "relatable") => void;
}

export default function StrategyOutput({ plan, activeHookType, onSelectHookType }: Props) {
  const [copiedSection, setCopiedSection] = useState<string | null>(null);

  const copyToClipboard = (text: string, sectionId: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionId);
    setTimeout(() => {
      setCopiedSection(null);
    }, 2000);
  };

  const getHookText = (type: "curiosity" | "visual" | "relatable") => {
    switch (type) {
      case "curiosity": return plan.hooks.curiosityHook;
      case "visual": return plan.hooks.visualActionHook;
      case "relatable": return plan.hooks.relatableHook;
    }
  };

  // Full representation content helper
  const getFullStrategyCopyableText = () => {
    return `INSTAGRAM CONTENT PLAN (Generated by Instagram Creative Partner)
======================================================
1. TRANSLATION & CONCEPT INTERPRETATION
- Raw Content Goal: ${plan.translatedConcept}
- Core Audience Emotion: ${plan.conceptEmotion}

2. FORMAT STRATEGY
- Recommended Format: ${plan.strategy.bestFormat}
- Strategy reasoning: ${plan.strategy.formatReasoning}
- Core Angle (DM Share Trigger): ${plan.strategy.coreAngle}

3. HOOK OPTIONS
- Curiosity Hook: ${plan.hooks.curiosityHook}
- Visual/Action Hook: ${plan.hooks.visualActionHook}
- Relatable Hook: ${plan.hooks.relatableHook}

4. RETENTION CONTENT ARC
- 0-3 Seconds: ${plan.contentArc.zeroToThreeSeconds}
- 3-15 Seconds: ${plan.contentArc.threeToFifteenSeconds}
- 15+ Seconds: ${plan.contentArc.fifteenPlusSeconds}
- CTA (Call to Action): ${plan.contentArc.cta}

5. SEO CAPTION
- First Line Secondary Hook: ${plan.seoCaption.firstLine}
- Body: ${plan.seoCaption.body}
- Hashtags: ${plan.seoCaption.hashtags.join(" ")}
======================================================`;
  };

  return (
    <div className="space-y-6">
      
      {/* 1. Concepts Translate Banner */}
      <div className="bg-white/[0.02] border border-white/5 rounded-2xl p-6 backdrop-blur-xl transition-all hover:border-[#ff4f00]/30 shadow-[0_8px_30px_rgba(0,0,0,0.4)]">
        <div className="flex items-start justify-between gap-4">
          <div className="space-y-3 flex-1">
            <h4 className="text-[10px] font-mono tracking-widest text-[#ff4f00] uppercase">
              Concept Intent
            </h4>
            <p className="text-base text-white leading-relaxed font-medium">
              "{plan.translatedConcept}"
            </p>
            <div className="flex items-center gap-2 text-xs font-mono mt-2">
              <span className="text-zinc-500">Emotional Trigger:</span>
              <span className="px-2.5 py-1 rounded-md bg-[#ff4f00]/10 text-[#ff4f00] border border-[#ff4f00]/20">
                {plan.conceptEmotion}
              </span>
            </div>
          </div>
          
          <button
            onClick={() => copyToClipboard(getFullStrategyCopyableText(), "full")}
            className="flex-shrink-0 text-zinc-400 hover:text-white px-3 py-1.5 rounded bg-white/5 hover:bg-white/10 flex items-center gap-1.5 text-xs transition-colors"
          >
            {copiedSection === "full" ? (
              <>
                <Check className="w-3.5 h-3.5" />
                <span>Copied</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy All</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* 2. Format Card */}
      <div className="bg-white/[0.02] border border-white/5 rounded-2xl p-6 backdrop-blur-xl shadow-[0_8px_30px_rgba(0,0,0,0.4)]">
        <div className="flex items-center justify-between border-b border-white/5 pb-4 mb-5">
          <h3 className="text-base font-display font-medium text-white">Required Format</h3>
          <span className="text-xs font-mono bg-gradient-to-r from-[#ff4f00] to-[#ff7300] px-3 py-1 rounded-full text-white font-medium shadow-[0_0_15px_rgba(255,79,0,0.3)]">
            {plan.strategy.bestFormat}
          </span>
        </div>
        
        <div className="grid md:grid-cols-2 gap-6">
          <div className="space-y-3">
            <h4 className="text-[10px] font-mono text-zinc-500 uppercase tracking-widest flex items-center gap-1.5"><Sparkles className="w-3 h-3" /> Reasoning</h4>
            <p className="text-sm text-zinc-300 leading-relaxed bg-black/40 border border-white/5 p-4 rounded-xl">
              {plan.strategy.formatReasoning}
            </p>
          </div>
          <div className="space-y-3">
            <h4 className="text-[10px] font-mono text-[#ff4f00] uppercase tracking-widest">Share Trigger</h4>
            <p className="text-sm text-white leading-relaxed bg-black/40 border border-white/5 p-4 rounded-xl">
              {plan.strategy.coreAngle}
            </p>
          </div>
        </div>
      </div>

      {/* 3. Hooks Box */}
      <div className="bg-white/[0.02] border border-white/5 rounded-2xl p-6 backdrop-blur-xl shadow-[0_8px_30px_rgba(0,0,0,0.4)]">
        <div className="flex items-center justify-between border-b border-white/5 pb-4 mb-5">
          <h3 className="text-base font-display font-medium text-white">Hook Selection (3-Second)</h3>
        </div>

        <div className="space-y-3">
          {/* Curiosity Hook */}
          <div 
            onClick={() => onSelectHookType("curiosity")}
            className={`p-5 rounded-xl border transition-all cursor-pointer flex justify-between items-start gap-4 ${
              activeHookType === "curiosity" 
                ? "bg-[#ff4f00]/5 border-[#ff4f00]/30 shadow-[0_4px_20px_rgba(255,79,0,0.1)]" 
                : "bg-black/40 border-white/5 hover:border-white/10"
            }`}
          >
            <div className="space-y-2 flex-1">
              <span className={`text-[10px] font-mono font-bold tracking-widest uppercase ${activeHookType === 'curiosity' ? 'text-[#ff4f00]' : 'text-zinc-500'}`}>
                Curiosity
              </span>
              <p className="text-sm text-zinc-200 leading-relaxed pr-4">
                "{plan.hooks.curiosityHook}"
              </p>
            </div>
            <button
              onClick={(e) => {
                e.stopPropagation();
                copyToClipboard(plan.hooks.curiosityHook, "curiosity");
              }}
              className="text-zinc-500 hover:text-zinc-300 p-1 rounded"
            >
              {copiedSection === "curiosity" ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            </button>
          </div>

          {/* Visual Hook */}
          <div 
            onClick={() => onSelectHookType("visual")}
            className={`p-5 rounded-xl border transition-all cursor-pointer flex justify-between items-start gap-4 ${
              activeHookType === "visual" 
                ? "bg-[#ff4f00]/5 border-[#ff4f00]/30 shadow-[0_4px_20px_rgba(255,79,0,0.1)]" 
                : "bg-black/40 border-white/5 hover:border-white/10"
            }`}
          >
            <div className="space-y-2 flex-1">
              <div className="flex items-center gap-2">
                <span className={`text-[10px] font-mono font-bold tracking-widest uppercase ${activeHookType === 'visual' ? 'text-[#ff4f00]' : 'text-zinc-500'}`}>
                  Visual / Action
                </span>
                <span className="text-[8px] font-mono bg-white/10 text-white px-2 py-0.5 rounded-full">Requires Props</span>
              </div>
              <p className="text-sm text-zinc-200 leading-relaxed pr-4">
                "{plan.hooks.visualActionHook}"
              </p>
            </div>
            <button
              onClick={(e) => {
                e.stopPropagation();
                copyToClipboard(plan.hooks.visualActionHook, "visual");
              }}
              className="text-zinc-500 hover:text-zinc-300 p-1 rounded"
            >
              {copiedSection === "visual" ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            </button>
          </div>

          {/* Relatable Callout Hook */}
          <div 
            onClick={() => onSelectHookType("relatable")}
            className={`p-5 rounded-xl border transition-all cursor-pointer flex justify-between items-start gap-4 ${
              activeHookType === "relatable" 
                ? "bg-[#ff4f00]/5 border-[#ff4f00]/30 shadow-[0_4px_20px_rgba(255,79,0,0.1)]" 
                : "bg-black/40 border-white/5 hover:border-white/10"
            }`}
          >
            <div className="space-y-2 flex-1">
              <span className={`text-[10px] font-mono font-bold tracking-widest uppercase ${activeHookType === 'relatable' ? 'text-[#ff4f00]' : 'text-zinc-500'}`}>
                Relatable
              </span>
              <p className="text-sm text-zinc-200 leading-relaxed pr-4">
                "{plan.hooks.relatableHook}"
              </p>
            </div>
            <button
              onClick={(e) => {
                e.stopPropagation();
                copyToClipboard(plan.hooks.relatableHook, "relatable");
              }}
              className="text-zinc-500 hover:text-zinc-300 p-1 rounded"
            >
              {copiedSection === "relatable" ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            </button>
          </div>
        </div>
      </div>

      {/* 4. Chronological Retention Script */}
      <div className="bg-white/[0.02] border border-white/5 rounded-2xl p-6 backdrop-blur-xl shadow-[0_8px_30px_rgba(0,0,0,0.4)]">
        <div className="flex items-center justify-between border-b border-white/5 pb-4 mb-6">
          <h3 className="text-base font-display font-medium text-white">Video Script Sequence</h3>
          <button
            onClick={() => {
              const text = `VIDEO SCRIPT:\n0-3s Hook: ${getHookText(activeHookType)}\n3-15s Value: ${plan.contentArc.threeToFifteenSeconds}\n15s Payload Climax: ${plan.contentArc.fifteenPlusSeconds}\n👉 CTA: ${plan.contentArc.cta}`;
              copyToClipboard(text, "script");
            }}
            className="text-xs text-zinc-400 hover:text-white flex items-center gap-1.5"
          >
            {copiedSection === "script" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
            <span>Copy Block</span>
          </button>
        </div>

        <div className="relative pl-3 space-y-10 before:absolute before:left-3 before:top-2 before:bottom-2 before:w-px before:bg-gradient-to-b before:from-[#ff4f00] before:via-[#ff4f00]/30 before:to-white/10">
          
          {/* Timing Section 1: Hook */}
          <div className="relative pl-8">
            <div className="absolute left-[-4.5px] top-1.5 w-[11px] h-[11px] rounded-full bg-[#ff4f00] ring-4 ring-[#050505] shadow-[0_0_10px_rgba(255,79,0,0.8)]" />
            <span className="text-[10px] font-mono text-[#ff4f00] tracking-widest uppercase block mb-2 font-bold">0 - 3s: Hook</span>
            <p className="text-base text-white leading-relaxed">
              "{getHookText(activeHookType)}"
            </p>
          </div>

          {/* Timing Section 2: Value Delivery */}
          <div className="relative pl-8">
            <div className="absolute left-[-3.5px] top-1.5 w-2 h-2 rounded-full bg-[#ff4f00]/50 ring-4 ring-[#050505]" />
            <span className="text-[10px] font-mono text-zinc-400 tracking-widest uppercase block mb-2">3 - 15s: Value</span>
            <p className="text-sm text-zinc-300 leading-relaxed">
              {plan.contentArc.threeToFifteenSeconds}
            </p>
          </div>

          {/* Timing Section 3: Climax Payoff */}
          <div className="relative pl-8">
            <div className="absolute left-[-3.5px] top-1.5 w-2 h-2 rounded-full bg-[#ff4f00]/50 ring-4 ring-[#050505]" />
            <span className="text-[10px] font-mono text-zinc-400 tracking-widest uppercase block mb-2">15s+: Climax</span>
            <p className="text-sm text-zinc-300 leading-relaxed">
              {plan.contentArc.fifteenPlusSeconds}
            </p>
          </div>

          {/* Timing Section 4: Frictionless Action Call */}
          <div className="relative pl-8">
            <div className="absolute left-[-4.5px] top-1.5 w-[11px] h-[11px] rounded-full bg-white ring-4 ring-[#050505]" />
            <span className="text-[10px] font-mono text-white tracking-widest uppercase block mb-2">CTA</span>
            <p className="text-sm text-white font-medium">
              {plan.contentArc.cta}
            </p>
          </div>

        </div>
      </div>

      {/* 5. SEO Optimized Caption & Tags */}
      <div className="bg-white/[0.02] border border-white/5 rounded-2xl p-6 backdrop-blur-xl shadow-[0_8px_30px_rgba(0,0,0,0.4)]">
        <div className="flex items-center justify-between border-b border-white/5 pb-4 mb-5">
          <h3 className="text-base font-display font-medium text-white">SEO Caption</h3>
          <button
            onClick={() => {
              const text = `${plan.seoCaption.firstLine}\n\n${plan.seoCaption.body}\n\n${plan.seoCaption.hashtags.join(" ")}`;
              copyToClipboard(text, "caption");
            }}
            className="text-xs text-zinc-400 hover:text-white flex items-center gap-1.5"
          >
            {copiedSection === "caption" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
            <span>Copy</span>
          </button>
        </div>

        <div className="bg-black/40 border border-white/5 p-5 rounded-xl space-y-5 select-text">
          <div className="space-y-2">
            <span className="text-[10px] font-mono text-[#ff4f00] uppercase tracking-widest block">First Line</span>
            <p className="text-base text-white font-medium select-all">
              {plan.seoCaption.firstLine}
            </p>
          </div>

          <div className="space-y-2">
            <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-widest block">Body</span>
            <p className="text-sm text-zinc-300 leading-relaxed whitespace-pre-line select-all">
              {plan.seoCaption.body}
            </p>
          </div>

          <div className="space-y-3 pt-3 border-t border-white/5">
            <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-widest block">Tags</span>
            <div className="flex flex-wrap gap-2 text-xs text-[#ff4f00] font-mono">
              {plan.seoCaption.hashtags.map((tag, i) => (
                <span key={i} className="select-all px-2 py-1 bg-[#ff4f00]/10 rounded-md border border-[#ff4f00]/20">{tag}</span>
              ))}
            </div>
          </div>
        </div>
      </div>

    </div>
  );
}
